Add click events
FlowingCode/GoogleMapsAddon pull request #20
Opened 2021-01-05 18:16 UTC by ngonzalezpazFC

Close #18

2021-01-05 18:21 UTC, javier-godoy requested changes

2021-01-05 18:21 UTC, javier-godoy commented on src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMap.java
> +					.readValue(latLng.toJson(), HashMap.class);
I understand that `latLng` is a JSON object. The following should work:
```
elemental.json.JsonValue latLng;
lat = ((JsonObject)latLng).getNumber("lat");
lng = ((JsonObject)latLng).getNumber("lng");
```

2021-01-06 16:53 UTC, javier-godoy approved these changes

2021-01-06 16:55 UTC, merged

2021-01-06 18:37 UTC, javier-godoy commented
@ngonzalezpazFC Since GoogleMapClickEvent and GoogleMapRightClickEvent have both the same properties, does it make sense to introduce an abstract class `GoogleMapClickEvent` and have `GoogleMapLeftClickEvent` and `GoogleMapRightClickEvent` both extend from it?

2021-01-06 18:42 UTC, ngonzalezpazFC commented
> 
> 
> @ngonzalezpazFC Since GoogleMapClickEvent and GoogleMapRightClickEvent have both the same properties, does it make sense to introduce an abstract class `GoogleMapClickEvent` and have `GoogleMapLeftClickEvent` and `GoogleMapRightClickEvent` both extend from it?

Yes, I think is a good idea to avoid code duplication. Should the abstract class be in a separated file?

2021-01-07 12:11 UTC, javier-godoy commented
> > @ngonzalezpazFC Since GoogleMapClickEvent and GoogleMapRightClickEvent have both the same properties, does it make sense to introduce an abstract class `GoogleMapClickEvent` and have `GoogleMapLeftClickEvent` and `GoogleMapRightClickEvent` both extend from it?
> 
> Yes, I think is a good idea to avoid code duplication. Should the abstract class be in a separated file?

I think it's fine in the same file.

2021-01-07 13:41 UTC, javier-godoy reviewed
Would you consider renaming it as follows?
 AbstractGoogleMapClickEvent -> GoogleMapClickEvent
 GoogleMapClickEvent -> GoogleMapLeftClickEvent 

Even better, instead of mapping the event with annotations, perhaps we can do:
```
public Registration addClickListener(
	DomListenerRegistration registration = this.getElement().addEventListener("google-map-rightclick", ev->{
	JsonObject latLng = ev.getEventData().get("event.detail.latLng");
	listener.click(new GoogleMapClickEvent(this,true,latLng));
	}).addEventData("event.detail.latLng");
    return registration::remove;
}
```
That way we'll avoid using different classes for the left and right clicks.