feat: add method to obtain the map bounds
FlowingCode/GoogleMapsAddon pull request #99
Opened 2023-08-15 19:17 UTC by paodb

Close #93

2023-08-15 19:36 UTC, javier-godoy requested changes

2023-08-15 19:36 UTC, javier-godoy commented on src/main/java/com/flowingcode/vaadin/addons/googlemaps/LatLonBounds.java
> +  public double getSouth() {
Use lombok `@Getter` and `@Setter`

2023-08-15 19:36 UTC, javier-godoy commented on src/main/java/com/flowingcode/vaadin/addons/googlemaps/LatLonBounds.java
> +  public String toString() {
Annotate the class with`@ToString(includeFieldNames=true)` instead. See https://projectlombok.org/features/ToString

2023-08-30 19:41 UTC, paodb commented on src/main/java/com/flowingcode/vaadin/addons/googlemaps/LatLonBounds.java
> +  public double getSouth() {
Lombok is not being used in the add-on. No need to replace setters/getters.

2023-08-30 19:41 UTC, paodb commented on src/main/java/com/flowingcode/vaadin/addons/googlemaps/LatLonBounds.java
> +  public String toString() {
Lombok is not being used in the add-on.

2023-08-31 12:19 UTC, mlopezFC approved these changes
I approve this change. Regarding the lombok thing, we should create another ticket to discuss what to do.

2023-08-31 12:26 UTC, merged